# Name of your site (displayed in the header)
name: Name Corp

# Short bio or description (displayed in the header)
description: Descripció curta del Web Site

alternativa: Una alternativa saludable al menjar ràpid.
natural: Cuina amb amor, amb productes naturals i de proximitat.
terra: Receptes de la terra de tota la vida.

premis: Text Destacat per a la pagina principal

# Horari
dilluns: de 13h a 16h
dimdium: De 13h a 16h / de 19h a 23h

# Seu Principal
city: Ciutat
location: C/ nom del carrer, 08911 Població, Ciutat
phone: +34 933 80 00 00
email: correu@gmail.com

# Seu Alternativa
city2: Arenas
location2: C/ nom del carrer, 08911 Població, Ciutat
phone2: +34 933 80 00 01
email2: correu2@gmail.com

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/36928139?s=460&v=4
logo: ./hipertextos/brand/bonrollo.svg


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: xxx@gmail.com
  facebook: Fa
  instagram: In
  twitter: Tw
  linkedin:
  pinterest:
  youtube:
  googleplus: 
  tripadvisor:
  flickr:
  github:
  behance:  
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  rss: true

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.weburl.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Defaults
defaults:
  -
    scope:
      path: "assets/bio"
    values:
      image: true
